version: 2
jobs:
  build:
    resource_class: medium
    working_directory: ~/ldbc/ldbc_snb_datagen
    docker:
      - image: ldbc/datagen-build:0.0.1
    steps:
      - checkout
      - run: mvn -ntp test
      
