version: 2
jobs:
  build:
    resource_class: medium
    working_directory: ~/ldbc/ldbc_snb_datagen
    docker:
      - image: ldbc/datagen-build:0.0.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - m2-dep-pom:{{ checksum "pom.xml" }}-
            - m2-dep-branch:{{ .Branch }}-
            - m2-dep-branch:dev-
      - run: mvn -ntp clean test-compile
      - save_cache:
        key: m2-dep-branch:{{ .Branch }}-{{ epoch }}
        paths:
          - ~/.m2/repository
      - save_cache:
        key: m2-dep-pom:{{ checksum "pom.xml" }}-{{ epoch }}
        paths:
          - ~/.m2/repository
      - run: mvn -ntp test
      
